### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by 404answernotfound** [404answernotfound/environtechnical#4]
The website needs to be translated.

Files for translations can be found inside the `locales` folder.

The file `next.config.js` should also be changed by adding the `es` string to the available translations.

**Comment by i-penr** [comment]
I think I can do this. Can you assign it to me?

**Comment by 404answernotfound** [comment]
> I think I can do this. Can you assign it to me?

Sure, let me know if you need any help :)
